// Service worker aplikácie ZBROJÁK.
// Cieľ: po prvom otvorení funguje aplikácia aj bez internetu — v aute, vo vlaku,
// v čakárni pred skúškou. Skripty a dáta sú na Supabase, shell na GitHub Pages,
// takže sa cachujú obe domény.

const VERSION = 'zbrojak-98f29f29';
const B = 'https://wjgbffhasgwbqecfarst.supabase.co/storage/v1/object/public/zbrojak/';

const SHELL = [
  './',
  './index.html',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png'
];

const ASSETS = [
  B + 'css/app.css',
  B + 'data/campaign.js',
  B + 'data/dilemmas.js',
  B + 'data/drills.js',
  B + 'data/explain.js',
  B + 'data/facts.js',
  B + 'data/law.js',
  B + 'data/medic.js',
  B + 'data/pathway.js',
  B + 'data/patrol.js',
  B + 'data/questions.js',
  B + 'data/rubrics.js',
  B + 'data/scenarios.js',
  B + 'data/weapons.js',
  B + 'js/anatomy.js',
  B + 'js/anatomy3d.js',
  B + 'js/answerbox.js',
  B + 'js/app.js',
  B + 'js/audio.js',
  B + 'js/games/dilemma.js',
  B + 'js/games/fieldstrip.js',
  B + 'js/games/medic.js',
  B + 'js/games/patrol.js',
  B + 'js/games/rangefire.js',
  B + 'js/games/sorter.js',
  B + 'js/games/vault.js',
  B + 'js/grade.js',
  B + 'js/search.js',
  B + 'js/srs.js',
  B + 'js/store.js',
  B + 'js/three/kit.js',
  B + 'js/three/pistol.js',
  B + 'js/three/revolver.js',
  B + 'js/three/rifle.js',
  B + 'js/three/viewer.js',
  B + 'js/ui.js',
  B + 'js/views/anatomyview.js',
  B + 'js/views/ask.js',
  B + 'js/views/bank.js',
  B + 'js/views/blitz.js',
  B + 'js/views/campaign.js',
  B + 'js/views/cards.js',
  B + 'js/views/common.js',
  B + 'js/views/exam.js',
  B + 'js/views/home.js',
  B + 'js/views/law.js',
  B + 'js/views/path.js',
  B + 'js/views/profile.js',
  B + 'js/views/range.js',
  B + 'js/views/scenario.js',
  B + 'js/views/stats.js',
  B + 'js/views/triage.js',
  B + 'js/weapon.js',
  B + 'src/content/campaign/art/m1.js',
  B + 'src/content/campaign/art/m2.js',
  B + 'src/content/campaign/art/m3.js',
  B + 'src/content/campaign/art/m4.js',
  B + 'src/content/campaign/art/m5.js',
  B + 'src/content/campaign/art/m6.js',
  B + 'src/content/campaign/art/m7.js',
  B + 'src/content/campaign/art/m8.js',
  B + 'src/content/campaign/index.js',
  B + 'src/content/campaign/missions/m1.js',
  B + 'src/content/campaign/missions/m2.js',
  B + 'src/content/campaign/missions/m3.js',
  B + 'src/content/campaign/missions/m4.js',
  B + 'src/content/campaign/missions/m5.js',
  B + 'src/content/campaign/missions/m6.js',
  B + 'src/content/campaign/missions/m7.js',
  B + 'src/content/campaign/missions/m8.js',
  B + 'src/content/campaign/ranks.js',
  B + 'src/content/dilemma/index.js',
  B + 'src/content/dilemma/scenes/s01-kroky-ktore-sa-vzdaluju.js',
  B + 'src/content/dilemma/scenes/s02-zajtra-o-siestej.js',
  B + 'src/content/dilemma/scenes/s03-sklo-medzi-vami.js',
  B + 'src/content/dilemma/scenes/s04-noz-na-medziposchodi.js',
  B + 'src/content/dilemma/scenes/s05-cierny-predmet.js',
  B + 'src/content/dilemma/scenes/s06-dva-psy-medzi-stromami.js',
  B + 'src/content/dilemma/scenes/s07-tri-hodiny-rano.js',
  B + 'src/content/dilemma/scenes/s08-za-kontajnermi.js',
  B + 'src/content/dilemma/scenes/s09-kabelka-a-dvadsat-metrov.js',
  B + 'src/content/dilemma/scenes/s10-styria-a-flasa.js',
  B + 'src/content/dilemma/scenes/s11-sused-na-tretom.js',
  B + 'src/content/dilemma/scenes/s12-dodavka-pri-kolni.js',
  B + 'src/content/dilemma/scenes/s13-sekundy-po-vystrele.js',
  B + 'src/content/dilemma/scenes/s14-hlaven-ktora-sa-otaca.js',
  B + 'src/content/drills/index.js',
  B + 'src/content/drills/part-a.js',
  B + 'src/content/drills/part-b.js',
  B + 'src/content/drills/part-c.js',
  B + 'src/content/drills/part-d.js',
  B + 'src/content/drills/part-e.js',
  B + 'src/content/facts/index.js',
  B + 'src/content/facts/part-a.js',
  B + 'src/content/facts/part-b.js',
  B + 'src/content/facts/part-c.js',
  B + 'src/content/facts/part-d.js',
  B + 'src/content/facts/part-e.js',
  B + 'src/content/medic/brucho.js',
  B + 'src/content/medic/hlava.js',
  B + 'src/content/medic/hrudnik.js',
  B + 'src/content/medic/index.js',
  B + 'src/content/medic/krk.js',
  B + 'src/content/medic/plyn.js',
  B + 'src/content/medic/stehno.js',
  B + 'src/content/medic/triedenie.js',
  B + 'src/content/medic/zastava.js',
  B + 'src/content/pathway/fees.js',
  B + 'src/content/pathway/groups.js',
  B + 'src/content/pathway/index.js',
  B + 'src/content/pathway/steps.js',
  B + 'src/content/patrol/cestna-kontrola.js',
  B + 'src/content/patrol/doklady-manipulacia.js',
  B + 'src/content/patrol/dychova-skuska.js',
  B + 'src/content/patrol/index.js',
  B + 'src/content/patrol/nutna-obrana.js',
  B + 'src/content/patrol/prevoz-vystava.js',
  B + 'src/content/patrol/strelnica.js',
  B + 'src/content/patrol/sud.js',
  B + 'src/content/patrol/zbierka-doma.js',
  B + 'src/content/questions/index.js',
  B + 'src/content/questions/part-a.js',
  B + 'src/content/questions/part-b.js',
  B + 'src/content/questions/part-c.js',
  B + 'src/content/questions/part-d.js',
  B + 'src/content/questions/part-e.js',
  B + 'src/content/questions/parts.js',
  B + 'src/content/scenarios/range/index.js',
  B + 'src/content/scenarios/range/r-koniec.js',
  B + 'src/content/scenarios/range/r-porucha.js',
  B + 'src/content/scenarios/range/r-prevzatie.js',
  B + 'src/content/scenarios/range/r-prichod.js',
  B + 'src/content/scenarios/range/r-strelba.js',
  B + 'src/content/scenarios/triage/index.js',
  B + 'src/content/scenarios/triage/t-bezvedomie.js',
  B + 'src/content/scenarios/triage/t-brucho.js',
  B + 'src/content/scenarios/triage/t-hrudnik.js',
  B + 'src/content/scenarios/triage/t-koncatina.js',
  B + 'src/content/sorter/index.js',
  B + 'src/content/sorter/weapons-a.js',
  B + 'src/content/sorter/weapons-b.js',
  B + 'src/content/sorter/weapons-c.js',
  B + 'src/content/sorter/weapons-d.js',
  B + 'src/content/weapon/parts.js',
  B + 'src/core/assert.js',
  B + 'src/core/dom.js',
  B + 'src/core/escape.js',
  B + 'src/core/format/date.js',
  B + 'src/core/format/plural.js',
  B + 'src/core/format/time.js',
  B + 'src/core/lazy.js',
  B + 'src/core/random.js',
  B + 'src/core/text/normalize.js',
  B + 'src/core/text/skeleton.js',
  B + 'src/core/text/stem.js',
  B + 'src/core/text/tokenize.js',
  B + 'src/domain/cite/label.js',
  B + 'src/domain/cite/parse.js',
  B + 'src/domain/cite/resolve.js',
  B + 'src/domain/exam/eligibility.js',
  B + 'src/domain/grade/concept.js',
  B + 'src/domain/grade/doc.js',
  B + 'src/domain/grade/fuzzy.js',
  B + 'src/domain/grade/index.js',
  B + 'src/domain/grade/negation.js',
  B + 'src/domain/grade/pattern.js',
  B + 'src/domain/grade/similarity.js',
  B + 'src/domain/grade/verdict.js',
  B + 'src/domain/grade/words.js',
  B + 'src/domain/search/corpus.js',
  B + 'src/domain/search/diversity.js',
  B + 'src/domain/search/idf.js',
  B + 'src/domain/search/index.js',
  B + 'src/domain/search/query.js',
  B + 'src/domain/search/rank.js',
  B + 'src/domain/search/suggest.js',
  B + 'src/domain/srs/schedule.js',
  B + 'src/domain/srs/sm2.js',
  B + 'src/domain/srs/stats.js',
  B + 'src/platform/audio/bank.js',
  B + 'src/platform/audio/context.js',
  B + 'src/platform/audio/gun.js',
  B + 'src/platform/audio/layers.js',
  B + 'src/platform/audio/play.js',
  B + 'src/platform/audio/reverb.js',
  B + 'src/platform/audio/synth.js',
  B + 'src/platform/media.js',
  B + 'src/platform/raf.js',
  B + 'src/platform/storage.js',
  B + 'src/platform/visibility.js',
  B + 'src/platform/webgl.js',
  B + 'src/state/backup.js',
  B + 'src/state/migrate.js',
  B + 'src/state/persist.js',
  B + 'src/state/sanitize.js',
  B + 'src/state/schema.js',
  B + 'src/state/slices/badges.js',
  B + 'src/state/slices/campaign.js',
  B + 'src/state/slices/checklist.js',
  B + 'src/state/slices/levels.js',
  B + 'src/state/slices/profile.js',
  B + 'src/state/slices/progress.js',
  B + 'src/state/slices/scores.js',
  B + 'src/state/slices/seen.js',
  B + 'src/state/slices/settings.js',
  B + 'src/state/slices/srs.js',
  B + 'src/state/store.js',
  B + 'src/ui/icons/icon.js',
  B + 'src/ui/icons/set.js',
];

// Veľké súbory — model zbrane, znenia zákonov, rubriky a vysvetľovač.
// Sťahujú sa až po inštalácii, aby prvé otvorenie nečakalo na dva megabajty.
const HEAVY = [
  B + 'src/content/explain/faq-1.js',
  B + 'src/content/explain/faq-2.js',
  B + 'src/content/explain/faq-3.js',
  B + 'src/content/explain/index.js',
  B + 'src/content/explain/sections-1.js',
  B + 'src/content/explain/sections-2.js',
  B + 'src/content/explain/sections-3.js',
  B + 'src/content/explain/terms-1.js',
  B + 'src/content/explain/terms-2.js',
  B + 'src/content/explain/terms-3.js',
  B + 'src/content/law/index.js',
  B + 'src/content/law/v555/index.js',
  B + 'src/content/law/v555/par-1-12.js',
  B + 'src/content/law/v555/par-13-13.js',
  B + 'src/content/law/v555/prilohy.js',
  B + 'src/content/law/z190/index.js',
  B + 'src/content/law/z190/par-1-11.js',
  B + 'src/content/law/z190/par-12-22.js',
  B + 'src/content/law/z190/par-23-31.js',
  B + 'src/content/law/z190/par-31a-38.js',
  B + 'src/content/law/z190/par-39-49.js',
  B + 'src/content/law/z190/par-50-62.js',
  B + 'src/content/law/z190/par-63-72a.js',
  B + 'src/content/law/z190/par-72b-74.js',
  B + 'src/content/law/z190/prilohy.js',
  B + 'src/content/rubrics/facts-a.js',
  B + 'src/content/rubrics/facts-b.js',
  B + 'src/content/rubrics/facts-c.js',
  B + 'src/content/rubrics/facts-d.js',
  B + 'src/content/rubrics/facts-e.js',
  B + 'src/content/rubrics/index.js',
  B + 'src/content/rubrics/questions-a.js',
  B + 'src/content/rubrics/questions-b.js',
  B + 'src/content/rubrics/questions-c.js',
  B + 'src/content/rubrics/questions-d.js',
  B + 'src/content/rubrics/questions-e.js',
  B + 'src/vendor/three.module.js',
  B + 'src/weapon/3d/anim/effects.js',
  B + 'src/weapon/3d/anim/motion.js',
  B + 'src/weapon/3d/anim/rest.js',
  B + 'src/weapon/3d/anim/timeline.js',
  B + 'src/weapon/3d/contract.js',
  B + 'src/weapon/3d/core/camera.js',
  B + 'src/weapon/3d/core/controls.js',
  B + 'src/weapon/3d/core/device.js',
  B + 'src/weapon/3d/core/env.js',
  B + 'src/weapon/3d/core/lights.js',
  B + 'src/weapon/3d/core/loop.js',
  B + 'src/weapon/3d/core/renderer.js',
  B + 'src/weapon/3d/core/resize.js',
  B + 'src/weapon/3d/core/shadow-plane.js',
  B + 'src/weapon/3d/core/viewer.js',
  B + 'src/weapon/3d/core/visibility.js',
  B + 'src/weapon/3d/kit/cartridge.js',
  B + 'src/weapon/3d/kit/dispose.js',
  B + 'src/weapon/3d/kit/extrude.js',
  B + 'src/weapon/3d/kit/helix.js',
  B + 'src/weapon/3d/kit/index.js',
  B + 'src/weapon/3d/kit/materials.js',
  B + 'src/weapon/3d/kit/rod.js',
  B + 'src/weapon/3d/kit/serrations.js',
  B + 'src/weapon/3d/kit/shadows.js',
  B + 'src/weapon/3d/kit/shapes.js',
  B + 'src/weapon/3d/kit/stipple.js',
  B + 'src/weapon/3d/kit/tag.js',
  B + 'src/weapon/3d/kit/textures/grain.js',
  B + 'src/weapon/3d/kit/textures/noise.js',
  B + 'src/weapon/3d/kit/textures/punch.js',
  B + 'src/weapon/3d/kit/three.js',
  B + 'src/weapon/3d/kit/tube.js',
  B + 'src/weapon/3d/kit/units.js',
  B + 'src/weapon/3d/models/auto/anim/cycle.js',
  B + 'src/weapon/3d/models/auto/anim/feed.js',
  B + 'src/weapon/3d/models/auto/anim/fire.js',
  B + 'src/weapon/3d/models/auto/anim/index.js',
  B + 'src/weapon/3d/models/auto/anim/parts/kohut.js',
  B + 'src/weapon/3d/models/auto/anim/parts/komora.js',
  B + 'src/weapon/3d/models/auto/anim/parts/pruzina.js',
  B + 'src/weapon/3d/models/auto/anim/parts/spust.js',
  B + 'src/weapon/3d/models/auto/anim/parts/udernik.js',
  B + 'src/weapon/3d/models/auto/anim/parts/zasobnik.js',
  B + 'src/weapon/3d/models/auto/anim/parts/zaver.js',
  B + 'src/weapon/3d/models/auto/anim/parts/zavornik.js',
  B + 'src/weapon/3d/models/auto/anim/rest.js',
  B + 'src/weapon/3d/models/auto/anim/strip.js',
  B + 'src/weapon/3d/models/auto/build/hlaven.js',
  B + 'src/weapon/3d/models/auto/build/index.js',
  B + 'src/weapon/3d/models/auto/build/kohut.js',
  B + 'src/weapon/3d/models/auto/build/komora.js',
  B + 'src/weapon/3d/models/auto/build/mieridla.js',
  B + 'src/weapon/3d/models/auto/build/pazba.js',
  B + 'src/weapon/3d/models/auto/build/pruzina.js',
  B + 'src/weapon/3d/models/auto/build/puzdro.js',
  B + 'src/weapon/3d/models/auto/build/spust.js',
  B + 'src/weapon/3d/models/auto/build/udernik.js',
  B + 'src/weapon/3d/models/auto/build/ustie.js',
  B + 'src/weapon/3d/models/auto/build/zasobnik.js',
  B + 'src/weapon/3d/models/auto/build/zaver.js',
  B + 'src/weapon/3d/models/auto/build/zavornik.js',
  B + 'src/weapon/3d/models/auto/dims.js',
  B + 'src/weapon/3d/models/auto/index.js',
  B + 'src/weapon/3d/models/auto/meta.js',
  B + 'src/weapon/3d/models/auto/parts.js',
  B + 'src/weapon/3d/models/auto/sound.js',
  B + 'src/weapon/3d/models/auto/views.js',
  B + 'src/weapon/3d/models/pistol/anim/feed.js',
  B + 'src/weapon/3d/models/pistol/anim/fire.js',
  B + 'src/weapon/3d/models/pistol/anim/index.js',
  B + 'src/weapon/3d/models/pistol/anim/parts/hlaven.js',
  B + 'src/weapon/3d/models/pistol/anim/parts/komora.js',
  B + 'src/weapon/3d/models/pistol/anim/parts/pruzina.js',
  B + 'src/weapon/3d/models/pistol/anim/parts/puzdro.js',
  B + 'src/weapon/3d/models/pistol/anim/parts/spust.js',
  B + 'src/weapon/3d/models/pistol/anim/parts/udernik.js',
  B + 'src/weapon/3d/models/pistol/anim/parts/vlozna.js',
  B + 'src/weapon/3d/models/pistol/anim/parts/zasobnik.js',
  B + 'src/weapon/3d/models/pistol/anim/parts/zaver.js',
  B + 'src/weapon/3d/models/pistol/anim/parts/zavornik.js',
  B + 'src/weapon/3d/models/pistol/anim/rest.js',
  B + 'src/weapon/3d/models/pistol/anim/strip.js',
  B + 'src/weapon/3d/models/pistol/anim/tilt.js',
  B + 'src/weapon/3d/models/pistol/build/barrel.js',
  B + 'src/weapon/3d/models/pistol/build/index.js',
  B + 'src/weapon/3d/models/pistol/build/komora.js',
  B + 'src/weapon/3d/models/pistol/build/pruzina.js',
  B + 'src/weapon/3d/models/pistol/build/puzdro.js',
  B + 'src/weapon/3d/models/pistol/build/sights.js',
  B + 'src/weapon/3d/models/pistol/build/slide.js',
  B + 'src/weapon/3d/models/pistol/build/spust.js',
  B + 'src/weapon/3d/models/pistol/build/telo.js',
  B + 'src/weapon/3d/models/pistol/build/udernik.js',
  B + 'src/weapon/3d/models/pistol/build/ustie.js',
  B + 'src/weapon/3d/models/pistol/build/vlozna.js',
  B + 'src/weapon/3d/models/pistol/build/zasobnik.js',
  B + 'src/weapon/3d/models/pistol/build/zavornik.js',
  B + 'src/weapon/3d/models/pistol/dims.js',
  B + 'src/weapon/3d/models/pistol/index.js',
  B + 'src/weapon/3d/models/pistol/meta.js',
  B + 'src/weapon/3d/models/pistol/parts.js',
  B + 'src/weapon/3d/models/pistol/sound.js',
  B + 'src/weapon/3d/models/pistol/views.js',
  B + 'src/weapon/3d/models/revolver/anim/feed.js',
  B + 'src/weapon/3d/models/revolver/anim/fire.js',
  B + 'src/weapon/3d/models/revolver/anim/index.js',
  B + 'src/weapon/3d/models/revolver/anim/parts/kohut.js',
  B + 'src/weapon/3d/models/revolver/anim/parts/komora.js',
  B + 'src/weapon/3d/models/revolver/anim/parts/spust.js',
  B + 'src/weapon/3d/models/revolver/anim/parts/udernik.js',
  B + 'src/weapon/3d/models/revolver/anim/parts/valec.js',
  B + 'src/weapon/3d/models/revolver/anim/parts/vlozna.js',
  B + 'src/weapon/3d/models/revolver/anim/rest.js',
  B + 'src/weapon/3d/models/revolver/anim/strip.js',
  B + 'src/weapon/3d/models/revolver/build/hlaven.js',
  B + 'src/weapon/3d/models/revolver/build/index.js',
  B + 'src/weapon/3d/models/revolver/build/kohut.js',
  B + 'src/weapon/3d/models/revolver/build/komora.js',
  B + 'src/weapon/3d/models/revolver/build/mieridla.js',
  B + 'src/weapon/3d/models/revolver/build/ram.js',
  B + 'src/weapon/3d/models/revolver/build/spust.js',
  B + 'src/weapon/3d/models/revolver/build/udernik.js',
  B + 'src/weapon/3d/models/revolver/build/ustie.js',
  B + 'src/weapon/3d/models/revolver/build/valec.js',
  B + 'src/weapon/3d/models/revolver/build/vlozna.js',
  B + 'src/weapon/3d/models/revolver/dims.js',
  B + 'src/weapon/3d/models/revolver/index.js',
  B + 'src/weapon/3d/models/revolver/meta.js',
  B + 'src/weapon/3d/models/revolver/parts.js',
  B + 'src/weapon/3d/models/revolver/sound.js',
  B + 'src/weapon/3d/models/revolver/views.js',
  B + 'src/weapon/3d/models/rifle/anim/cycle.js',
  B + 'src/weapon/3d/models/rifle/anim/feed.js',
  B + 'src/weapon/3d/models/rifle/anim/fire.js',
  B + 'src/weapon/3d/models/rifle/anim/index.js',
  B + 'src/weapon/3d/models/rifle/anim/parts/komora.js',
  B + 'src/weapon/3d/models/rifle/anim/parts/spust.js',
  B + 'src/weapon/3d/models/rifle/anim/parts/udernik.js',
  B + 'src/weapon/3d/models/rifle/anim/parts/vlozna.js',
  B + 'src/weapon/3d/models/rifle/anim/parts/zasobnik.js',
  B + 'src/weapon/3d/models/rifle/anim/parts/zaver.js',
  B + 'src/weapon/3d/models/rifle/anim/parts/zavornik.js',
  B + 'src/weapon/3d/models/rifle/anim/rest.js',
  B + 'src/weapon/3d/models/rifle/anim/strip.js',
  B + 'src/weapon/3d/models/rifle/build/hlaven.js',
  B + 'src/weapon/3d/models/rifle/build/index.js',
  B + 'src/weapon/3d/models/rifle/build/komora.js',
  B + 'src/weapon/3d/models/rifle/build/mieridla.js',
  B + 'src/weapon/3d/models/rifle/build/pazba.js',
  B + 'src/weapon/3d/models/rifle/build/puzdro.js',
  B + 'src/weapon/3d/models/rifle/build/spust.js',
  B + 'src/weapon/3d/models/rifle/build/udernik.js',
  B + 'src/weapon/3d/models/rifle/build/ustie.js',
  B + 'src/weapon/3d/models/rifle/build/vlozna.js',
  B + 'src/weapon/3d/models/rifle/build/zasobnik.js',
  B + 'src/weapon/3d/models/rifle/build/zaver.js',
  B + 'src/weapon/3d/models/rifle/build/zavornik.js',
  B + 'src/weapon/3d/models/rifle/dims.js',
  B + 'src/weapon/3d/models/rifle/index.js',
  B + 'src/weapon/3d/models/rifle/meta.js',
  B + 'src/weapon/3d/models/rifle/parts.js',
  B + 'src/weapon/3d/models/rifle/sound.js',
  B + 'src/weapon/3d/models/rifle/views.js',
  B + 'src/weapon/3d/models/shotgun/anim/feed.js',
  B + 'src/weapon/3d/models/shotgun/anim/fire.js',
  B + 'src/weapon/3d/models/shotgun/anim/index.js',
  B + 'src/weapon/3d/models/shotgun/anim/parts/kohut.js',
  B + 'src/weapon/3d/models/shotgun/anim/parts/komora.js',
  B + 'src/weapon/3d/models/shotgun/anim/parts/spust.js',
  B + 'src/weapon/3d/models/shotgun/anim/parts/udernik.js',
  B + 'src/weapon/3d/models/shotgun/anim/parts/vlozna.js',
  B + 'src/weapon/3d/models/shotgun/anim/parts/zasobnik.js',
  B + 'src/weapon/3d/models/shotgun/anim/parts/zaver.js',
  B + 'src/weapon/3d/models/shotgun/anim/parts/zavornik.js',
  B + 'src/weapon/3d/models/shotgun/anim/pump.js',
  B + 'src/weapon/3d/models/shotgun/anim/rest.js',
  B + 'src/weapon/3d/models/shotgun/anim/strip.js',
  B + 'src/weapon/3d/models/shotgun/build/hlaven.js',
  B + 'src/weapon/3d/models/shotgun/build/index.js',
  B + 'src/weapon/3d/models/shotgun/build/kohut.js',
  B + 'src/weapon/3d/models/shotgun/build/komora.js',
  B + 'src/weapon/3d/models/shotgun/build/mieridla.js',
  B + 'src/weapon/3d/models/shotgun/build/naboj.js',
  B + 'src/weapon/3d/models/shotgun/build/pazba.js',
  B + 'src/weapon/3d/models/shotgun/build/predpazbie.js',
  B + 'src/weapon/3d/models/shotgun/build/puzdro.js',
  B + 'src/weapon/3d/models/shotgun/build/spust.js',
  B + 'src/weapon/3d/models/shotgun/build/udernik.js',
  B + 'src/weapon/3d/models/shotgun/build/ustie.js',
  B + 'src/weapon/3d/models/shotgun/build/vlozna.js',
  B + 'src/weapon/3d/models/shotgun/build/zasobnik.js',
  B + 'src/weapon/3d/models/shotgun/build/zaver.js',
  B + 'src/weapon/3d/models/shotgun/build/zavornik.js',
  B + 'src/weapon/3d/models/shotgun/dims.js',
  B + 'src/weapon/3d/models/shotgun/index.js',
  B + 'src/weapon/3d/models/shotgun/meta.js',
  B + 'src/weapon/3d/models/shotgun/parts.js',
  B + 'src/weapon/3d/models/shotgun/sound.js',
  B + 'src/weapon/3d/models/shotgun/views.js',
  B + 'src/weapon/3d/panel/action-buttons.js',
  B + 'src/weapon/3d/panel/actions.js',
  B + 'src/weapon/3d/panel/api.js',
  B + 'src/weapon/3d/panel/captions.js',
  B + 'src/weapon/3d/panel/index.js',
  B + 'src/weapon/3d/panel/legend.js',
  B + 'src/weapon/3d/panel/outline.js',
  B + 'src/weapon/3d/panel/panel.js',
  B + 'src/weapon/3d/panel/part-buttons.js',
  B + 'src/weapon/3d/panel/picker.js',
  B + 'src/weapon/3d/panel/player.js',
  B + 'src/weapon/3d/panel/stage.js',
  B + 'src/weapon/3d/panel/weapon-switch.js',
  B + 'src/weapon/3d/panel/xray.js',
  B + 'src/weapon/3d/registry.js',
  B + 'src/weapon/3d/sound.js',
];

self.addEventListener('install', e => {
  e.waitUntil((async () => {
    const c = await caches.open(VERSION);
    // cache: 'reload' obchádza HTTP cache prehliadača — inak by sa do offline zásoby
    // dostala stará verzia vstupnej stránky
    const fresh = u => new Request(u, { cache: 'reload' });
    await Promise.all(SHELL.map(u => c.add(fresh(u)).catch(() => {})));
    await Promise.all(ASSETS.map(u => c.add(fresh(u)).catch(() => {})));
    // ťažké súbory dobehnú na pozadí; appka je použiteľná aj bez nich
    Promise.all(HEAVY.map(u => c.add(fresh(u)).catch(() => {})));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const ours = url.origin === self.location.origin || req.url.startsWith(B);
  if (!ours) return;

  e.respondWith((async () => {
    const cache = await caches.open(VERSION);

    // Vstupná stránka: najprv sieť, aby sa aktualizácia prejavila hneď;
    // bez siete padáme na uloženú kópiu, takže appka naštartuje aj offline.
    if (req.mode === 'navigate') {
      try {
        const r = await fetch(new Request(req.url, { cache: 'reload' }));
        if (r && r.ok) { cache.put('./index.html', r.clone()); cache.put('./', r.clone()); }
        return r;
      } catch (err) {
        return (await cache.match('./index.html')) || (await cache.match('./')) || Response.error();
      }
    }

    // Skripty, štýly a dáta: najprv cache (appka naskočí okamžite), obnova na pozadí.
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) {
      fetch(req).then(r => { if (r && r.ok) cache.put(req, r.clone()); }).catch(() => {});
      return hit;
    }
    const r = await fetch(req);
    if (r && r.ok) cache.put(req, r.clone());
    return r;
  })());
});

self.addEventListener('message', e => {
  if (e.data === 'skipWaiting') self.skipWaiting();
});
